### ISSUE TITLE
DateTime format read from JDBC connector is different from what is retrieved from Vantiq Type

### ISSUE THREAD

**Issue by liu-xiao-guo** [Vantiq/vantiq-extension-sources#142]
Following the following steps:

1) Read a DATETIME data type from MySQL using JDBC connector
2) Save the DATETIME into a type which has a DateTime in Vantiq system
3) Read back the DateTime from Vantiq system
4) Compare the DateTime from Vantiq to the original one read from JDBC connector

The two formats are not the same. It would be good to make both of them the same format to avoid internal conversion between to format.

**Comment by fhcarter** [comment]
The problem here is that there is no single canonical format.  Each database may use a different format.  We cannot match them (all).

Various databases will, internally, store dates using various forms. What you appear to be talking about here is the string format representation of the date.  If you need specific ones, you can manipulate the format using the date/time functions available.

If there's a specific issue where the actual date values (that is, the date/time that's represented) are wrong, that's an issue.  But not having identical default string formats for date values across all databases and/or VANTIQ isn't really a solvable problem.
