### ISSUE TITLE
Separate unit tests from integration tests

### ISSUE THREAD

**Issue by namirfa** [Vantiq/vantiq-extension-sources#261]
For all connectors as well as the extjsdk, separate the unit tests from the integration tests. This will allow us to run the unit tests on Jenkins without having to deal with the additional complexities of properly configuring the machine to run integration tests.

**Comment by rblumer4** [comment]
The Jenkins job can do multiple gradle commands, so we can start up that OPCUA server before running the tests, if that gets us more coverage easily.  Let me know if/when you want to work on that.

**Comment by fhcarter** [comment]
I think things are OK with just cleaned up `assumeTrue` & downstream handling.  At this point, with no special gradle properties defined, all the tests pass except those that appear to have real test issues.

**Comment by fhcarter** [comment]
[Jenkins run](https://jenkins.vantiq.com/jenkins/job/test-extension-sources/13/#showFailuresLink) showing failing tests -- all in TestConnectorSource  -- but some of the other extension source tests neither run nor compile since the TF, etc., environment variables aren't set up (nor are the places to which they should go).

**Comment by rblumer4** [comment]
Not sure what is needed for tensorFlow issues... Jenkins has those set up for the ag2rs tests, so maybe we need to add things to this pipeline, too?   Or does it need installation of something new?

Also, to prevent the build from "failing" & getting marked red, can you add this boilerplate to your `test` task in gradle?  
Then is should get marked "yellow" i.e. "unstable" instead.
(this is from ag2rs/build.gradle)
```
        def jenkinsHome = System.env.JENKINS_HOME

        if (jenkinsHome != null && jenkinsHome.length() > 0) {
            // continue the build on test failures, so that all tests get run & we get one total...
            // AND in jenkins, the build is continued with later reports collected...
            ignoreFailures = true
        }
```

If it helps, I can give you permission to edit this build-job on Jenkins, if you need to add/test with some environment variable settings.

**Comment by fhcarter** [comment]
for the Object Rec connector, we build Open CV from source -- I don't remember if they didn't have a distribution when we did it or we just didn't use it.  And it uses a different Java interface, I think, so it's not as simple as just dependencies.  Not a big deal, I don't think.  JDBC has similar issues (though there we could install a database & driver & set the environment variables.  Similarly JMS.

I think this is fine for now.  We can work to add others as required, but things will always be a bit different here so not to worried about it.  

I'll fix up the the build & check again.  Down to the two failures that are "real" failures (in the things tested).  I think they're test problems, but I'll leave them for Namir since he's been the one working on the test connector (which we really only use to test the k8s stuff).

**Comment by fhcarter** [comment]
Build moved <<red ball>> --> <<yellow ball>>.  Hurray!

**Comment by fhcarter** [comment]
@rblumer4 

BTW -- w/r/t opcua, we use an in-server server for testing, so things are OK there.  Those tests are now running.  The only issue was that I have a list of "public" servers -- presumably different implementations -- so a few of the tests try & connect to them all to verify that all is good.  One of those had gone a way.  I should improve the test so that if there's no there there it doesn't run -- but since the test is testing connectivity, it's a little tricky.

**Comment by rblumer4** [comment]
Updated Jenkins job to run tests now:  _vantiq-extension-sources-and-sdk_ and _vantiq-extension-sources-branch_
