### ISSUE TITLE
OBJREC:  Separate or merge overlapThreshold & threshold

### ISSUE THREAD

**Issue by fhcarter** [Vantiq/vantiq-extension-sources#57]
If the same concept, get rid of one.  If separate, make separate.

**Comment by namirfa** [comment]
From what I can tell, they seem to be separate values. 

The overlapThreshold is used to measure if two recognitions are different, which based on measuring how much they overlap with each other, against the overlapThreshold.

I don't know if it is necessary to add this value to the config, but I can. Otherwise I can just change it back to a constant. Let me know how I should proceed!
