### ISSUE TITLE
objectDetection Source is not using correct parameter for polling

### ISSUE THREAD

**Issue by bruden01** [Vantiq/vantiq-extension-sources#90]
I have reported a number of times that the object recognition source seems to buffer and fall behind.  So even though I have pollRate set to 3000 and the images are analyzed in about 1.5 seconds, the images are still processed sequentially instead of at the poll rate.

@namirfa had places in something on certain kinds of sources that would disconnect and reconnect, but I notice it still had the issue.

But I got to thinking the other day that the jdbc source doesn't or didn't use pollRate, it used pollTime.

So I added pollTime to my config and now everything works.  So I think there is at least 2 issues.

1 is that the correct paramater is pollTime, annd 2 if you don't include pollRate as well when you run the objectRecognitonSource you get an error so to run this correctly my confg looks like

```
{
   "objRecConfig": {
      "general": {
         "pollTime": 3000,
         "pollRate": 3000
      },
      "dataSource": {
         "camera": 0,
         "type": "camera"
      },
      "neuralNet": {
         "labelFile": "yolo.txt",
         "pbFile": "yolo.pb",
         "type": "yolo",
         "threshold": 0.24,
         "saveImage": "both",
         "outputDir": "images"
      }
   }
}
```

**Comment by namirfa** [comment]
@bruden01
I tested this issue by setting up a source with a nearly identical source configuration, but only using the pollRate. I held a timer up next to my head, and was able to confirm that the pollRate was being used correctly and that I did not need to use the "pollTime". 

In fact, setting the pollTime should have no effect on the configuration because we only ever check for a "pollRate" value in the source configuration. The expected behavior of the Object Recognition Source is that it will throw an error if no "pollRate" is set, or if the "allowQueries" field is not set since at least one of these is necessary to properly set up the source.

For consistency with the JDBC Source, and because it is a more accurate name, I will be changing the code to search for "pollTime" instead. To enable reverse compatibility for a limited time, I will make sure that the code accepts both "pollTime" and "pollRate" as valid source configuration options. Eventually, we will want to move away from using "pollRate".
